version: '3'

dotenv: ['.env','.env.dist']

tasks:
  install:
    platforms: [linux/arm64, linux/arm]
    cmds:
      - ./scripts/install.sh

  uninstall:
    platforms: [linux/arm64, linux/arm]
    cmds:
      - ./scripts/uninstall.sh

  update:
    platforms: [linux/arm64, linux/arm]
    cmds:
      - ./scripts/update.sh

  build:
    vars: 
      ARCH: arm
      OUTPUT_PATH: "./bin/health-service"
      APPLICATION_PATH: "./cmd/app"
    cmds:
      - env GOOS=linux GOARCH={{.ARCH}} go build -o {{.OUTPUT_PATH}} {{.APPLICATION_PATH}}
